### ISSUE TITLE
Layering for locals

### ISSUE THREAD

**Issue by Roxyrob** [boltops-tools/terraspace#104]
## Summary

Environment specific locals: devel, prod, ..

## Motivation

Sometimes locals contains complex data structures defining infra configuration. Having a layering of locals for different environments can be very useful to define different structure (number of element, size, ecc.).

**Comment by tongueroo** [comment]
Got mixed feelings here. Believe modules are like functions. Tfvars are inputs these functions. And locals are like temporary local variables within the function. 

Layering support for locals feels like reaching into a function and changing internal local variables.  It might be a little bit too much rope, when maybe it's a sign that the module can be refactored. Closing the issue for now. But am not completely closing up the idea. Feel like need to see some good examples of uses, though. 👍
