### ISSUE TITLE
Running terraspace using shell script

### ISSUE THREAD

**Issue by vivek221994** [boltops-tools/terraspace#106]
Hey!!
I wanted to know is it possible to run terraspace using shell scripts like taking the input variable from shell script command and deploying the services? my main intention of using terraspace is for deploying multiple modules at once.

This is possible while using terraform. but terraspace i am not getting it.

**Comment by tongueroo** [comment]
Terraspace currently uses the `-input=false` when it calls out to `terraspace` commands. IE:

    terraform apply -input=false

So it's not currently possible without a bunch of effort. This is currently done because it terraspace uses popen to call terraform so it can have more control over stdin and stdout.
