### ISSUE TITLE
terraspace test with steps 

### ISSUE THREAD

**Issue by infra-agilelab** [boltops-tools/terraspace#114]
Hello I'm writing here because I didn't received answer from forums
mainly I'd like to use the same approach I did for terratest , so splitting the test 
passing variable who define the stage (create, test, destroy) as I can following the doc
everytime I execute terraspace test another plan is applied an another resource it's create ,
ca someone give me some tips for this, sorry I'm quite new in ruby .

**Comment by tongueroo** [comment]
Answered in https://community.boltops.com/t/terratest-testing-module/708/2
