### ISSUE TITLE
Terraspace don't recognize dependency when use output in tf file

### ISSUE THREAD

**Issue by ByJacob** [boltops-tools/terraspace#115]
## Checklist

- [x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   linux      |
| Terraform        |   0.14.6      |
| Terraspace       |  0.6.9       |
| Ruby             |      ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]   |

---

## Expected Behaviour

`terraspace all graph` correct recognize dependencies
https://github.com/ByJacob/terraspace-bug-issues-115/blob/main/expected_image.png

## Current Behavior

`terraspace all graph` don't correct recognize dependencies
https://github.com/ByJacob/terraspace-bug-issues-115/blob/main/dependencies-20210531134254.png

## Step-by-step reproduction instructions

1. Get repository with sample code
2. Execute `terraspace all graph` in saple folder
3. Open dependencies png in `.terraspace-cache/graph`

## Code Sample

https://github.com/ByJacob/terraspace-bug-issues-115

## Solution Suggestion

Adding a relationship search in the tf file

**Comment by tongueroo** [comment]
The reason the graph doesnt have `test3 -> test1` is because it's not wired together as a dependency. Here's a PR to show it:

https://github.com/ByJacob/terraspace-bug-issues-115/pull/1

Believe them the graph is what you are trying to achieve

![dependencies-test3-to-test1](https://user-images.githubusercontent.com/4085/120250810-4e23f780-c234-11eb-9ac6-6b5acd43d071.png)

**Comment by ByJacob** [comment]
But it is wired here: https://github.com/ByJacob/terraspace-bug-issues-115/blob/main/sample/app/stacks/test3/main.tf. 

Why are links outside of tfvars not taken into account?

**Comment by tongueroo** [comment]
Sure. Only tfvars files are considered: https://terraspace.cloud/docs/dependencies/tfvars/considerations/#dependency-must-be-defined-in-tfvars

When `terraspace all` runs, it double processes tfvars files with ERB/ruby.  The 1st pass figures out the dependency graph. The 2nd pass fetches the output values from the resolved graph.

Would like to have links outside of tfvars be considered also, but think too much can go wrong with `main.tf`. So this is a current design decision. 

A possible better approach would be to use custom parser to resolve dependencies in the 1st pass. This would allow ERB/ruby to process files like `main.tf` in a single pass only, the current 2nd pass only. . Experimented with it on and off. Will consider PRs. No sweat either way of course.

**Comment by ByJacob** [comment]
Thank you for the explanation :) 

I looked through the documentation a dozen times, but I didn't notice this paragraph. I solved the above problem by defining depends_on in tfvars.
