### ISSUE TITLE
Update terraspace to work with terraform 1.0.0

### ISSUE THREAD

**Issue by gwvandesteeg** [boltops-tools/terraspace#121]
## Checklist

- [X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

```
Detected Terrspace version: 0.6.10
Detected Terraform bin: /root/.tfenv/bin/terraform
Detected Terraform v1.0.0
Terraspace requires Terraform v0.12.x and above
The installed version of terraform may not work with terraspace.
Recommend using at least terraform v0.12.x
If you would like to bypass this check. Use TS_VERSION_CHECK=0
```

## Expected Behaviour

Version check accepts terraform 1.0.0 as well as 0.12.x

**Comment by tongueroo** [comment]
See #120
