### ISSUE TITLE
Add integration GitHub with slack

### ISSUE THREAD

**Issue by ByJacob** [boltops-tools/terraspace#122]
## Summary

Add the ability to subscribe to the repository in slack. https://github.com/integrations/slack
## Motivation
I would like to be able to receive updates about the latest versions, but up-to-date and it doesn't work :c
```
/github subscribe boltops-tools/terraspace
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).
```

All users can use the function by monitoring activity in repositories on slack channels.
## Guide-level explanation

Unfortunately, I have not found documentation on how to add my application to this. The only message is the one given above.

**Comment by tongueroo** [comment]
Dug into this. Actually tested it with a workspace that I own. Looks like would have to give your slack workspace access to the read and **write** permissions to the terraspace repo. That's a no-go.
