### ISSUE TITLE
Why is terraspace deeply integrated to 'cloud provider' backend?

### ISSUE THREAD

**Issue by tckb** [boltops-tools/terraspace#130]
I really like the approach of `terraspace` but I am not quite sure if I am doing it wrong or this is by design. I would like to use `terraspace` without using _any_ cloud provider.  I am using a HTTP backend and currently it seems only AWS, Azure, GCP, TFC or TFE. Am I right in assuming this ?

**Comment by tongueroo** [comment]
First version, did this for convenience and to get it shipped. “Perfect is the enemy of shipping”. In the future, intend to decouple the cloud plugins. It’ll likely take some time though.

**Comment by tckb** [comment]
@tongueroo  Thanks for the quick reply! I was looking forward for a [**`http`** ](https://www.terraform.io/docs/language/settings/backends/http.html) backend. `gitlab` started  to offer  [terraform state](https://docs.gitlab.com/ee/user/infrastructure/terraform_state.html) maintenance  recently. It would be great to have this feature.

**Comment by tongueroo** [comment]
Interesting, didn’t know you were just talking about a http backend. Don’t see why that wouldn’t work. Maybe give it a test. If it errors, then file a Reproducible Bug issue. Leaving this issue as closed.

**Comment by tckb** [comment]
@tongueroo  I see - so it could be a bug 🤔 ?  Yes I will open a Bug thanks :-)
