### ISSUE TITLE
Version the docker images with semver

### ISSUE THREAD

**Issue by gwvandesteeg** [boltops-tools/terraspace#133]
## Summary

Package the docker images published to dockrhub with the semantic version of terraspace so that workloads can pin the image to the relevant version in case we encounter a breaking bug (such as https://github.com/boltops-tools/terraspace/issues/132)

## Motivation

This allows people to follow CICD best practices by explicitly specifying the version of the image they want to use and allow for testing of upgrades to the images to prevent breakage of existing workloads.

## Guide-level explanation

Currently we have daily builds of images available at (https://hub.docker.com/r/boltops/terraspace/tags?page=1&ordering=last_updated)
Which gives us images with the tags "alpine", "ubuntu", "debian", etc
Change the build process so that we get images tagged with the semantic version as well as the distro which would give us tags like:

- 0.6.11-ubuntu
- 0.6.11-alpine
- 0.6.11-centos
- 0.6.12-ubuntu
- 0.6.12-alpine
- 0.6.13-ubuntu, latest
- etc.

This will allow our CICD pipelines using these images to specify a specific version to ensure our builds stay functional until we've had the opportunity to test a new release with our pipelines to see if any issues occur.
..

## Reference-level explanation

Not sure what CICD automation is being used here to create the images.

## Drawbacks

You'll end up with more images hosted on docker hub

## Unresolved Questions

Nil

**Comment by gwvandesteeg** [comment]
Also ref: https://github.com/boltops-tools/terraspace-dockerfiles/issues/3

**Comment by tongueroo** [comment]
Done in https://github.com/boltops-tools/terraspace-dockerfiles/pull/6 

Docs: Docs: https://terraspace.cloud/docs/install/docker/versioning/
