### ISSUE TITLE
regular issue regarding gem dependencies faraday

### ISSUE THREAD

**Issue by Grummfy** [boltops-tools/terraspace#137]
## Checklist

- [x] Upgrade Terraspace: last version
- [x] Reproducibility: almost at each terraspace update
- [x] Code sample: no specific to code

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   GNU/Linux Ubuntu 21.04      |
| Terraform        |   1.0.4      |
| Terraspace       |    0.6.13-20210902100211     |
| Ruby             |   2.7.2p137      |

---

## Expected Behaviour

When there is an update of terraspace, to have just some basic dependency to update

## Current Behavior

When there is an update of terraspace, the installation require some update (OK), but most of the time I need to clear dependency to have a valid installation

"You have already activated faraday 1.7.0, but your Gemfile requires faraday 0.17.4. Prepending `bundle exec` to your command may solve this."

The issue seems to be related to faraday that are required in two different version (0.

## Step-by-step reproduction instructions

1. Create a project with terraspace, make sure everything run smoothly
2. Wait for terraspace update
3. Somme dependency issue will appears, update them individually or globally whatever) with "bundle update X"
4. run terraspace check, see the error with faraday 0.17.4 & 1.7.0 following the dependency
5. run `bundle clean --force` and `bundle install` to fix the issue

## Solution Suggestion

Force some dependency or at least check compatibility. In https://github.com/boltops-tools/terraspace/issues/135 it's seems there is the same issue, but upgrade ruby seems to solve the issue.

## Note
I'm not a ruby developer...

**Comment by tongueroo** [comment]
Bummer. Dug into this. Addressing this by improving the terraspace wrapper generated by the standalone installers. Details here: 

* https://terraspace.cloud/docs/install/standalone/details/#terraspace-wrapper  
* https://terraspace.cloud/docs/install/shim/

Believe this should resolve the issues. 🧐

In addition, added a friendly usage message with instructions on how to resolve if the error occurs. PR: https://github.com/boltops-tools/terraspace/pull/177  The standalone installer's new shim, as of terraspace 0.7.0 includes this smarter shim already.
