### ISSUE TITLE
New create plugin don't work

### ISSUE THREAD

**Issue by ByJacob** [boltops-tools/terraspace#143]
## Checklist

- [ X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [ X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

Docker `boltops/terraspace`

---

## Expected Behaviour

Create new module

## Current Behavior

```
/opt/terraspace/embedded/lib/ruby/gems/2.7.0/gems/terraspace-0.6.17/lib/terraspace/cli/new/plugin.rb:16:in `create_plugin': undefined method `core_template_source' for #<Terraspace::CLI::New::Plugin:0x000056121b5d4ca0> (NoMethodError)
```

## Step-by-step reproduction instructions

```
docker pull boltops/terraspace
docker run -ti boltops/terraspace
terraspace new plugin test
```

**Comment by tongueroo** [comment]
Closing in favor of #73
