### ISSUE TITLE
Tfenv Project-level Laying not working for all tfvars files

### ISSUE THREAD

**Issue by syphernl** [boltops-tools/terraspace#150]
## Checklist

- [X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | `Ubuntu 21.10` |
| Terraform        |  `1.0.11`       |
| Terraspace       | `0.6.18`         |
| Ruby             |   `2.7.4p191`      |

---

## Expected Behaviour

All project-wide tfvars copied to the build, as is [indicated in the documentation](https://terraspace.cloud/docs/tfvars/full-layering/#project-level-and-stack-level-layering) instead of only `base.tfstate` and `ENV.tfstate`

## Current Behavior

Not all `*.tfvars` files in the `config/terraform/tfvars` folder are being copied to the build dir, currently only `base.tfstate` and `ENV.tfstate` is being copied.
When put in `config/terraform` all of the files are being copied into the build directory.

## Step-by-step reproduction instructions

- Create `config/terraform/tfvars/global.tfvars` 
- Run `terraspace build modname`
- See that the `global.tfvars` is not copied to the build folder
- Move the `global.tfvars` one folder up (to `config/terraform`)
- Run `terraspace build modname`
- See that the `global.tfvars` _is_ copied to the build folder

**Comment by tongueroo** [comment]
So this is by design. Not all files are copied over so layer ordering can be controlled conventionally without having to prefix files with 1,2,etc. Makes for pretty tfvar file names. Instead of using `global.tvars`, use a project-level `base.tfvars`

Added a note to the docs to help point this out: https://github.com/boltops-tools/terraspace-docs/commit/25af11f1c2bf4b97d1fda0e532b05bf430d32f11
