### ISSUE TITLE
[Documentation needed] Need help around using env variable for backend.tf for terraspace init

### ISSUE THREAD

**Issue by yisyang** [boltops-tools/terraspace#160]
The [quick start documentations](https://terraspace.cloud/docs/learn/aws/) are pretty good about getting started with AWS and the like, likely due to the ability to use `~/.aws/credentials` and vendor-related cli tools and env variables.

Here I'd like to use the http backend (specifically the Gitlab backend), and I've gotten this far.

config/terraform/backend.tf
```
  backend "http" {
    address = "<%= expansion('https://gitlab.com/api/v4/projects/[PROJECT_ID]/terraform/state/:ENV') %>"
    lock_address = "<%= expansion('https://gitlab.com/api/v4/projects/[PROJECT_ID]/terraform/state/:ENV/lock') %>"
    unlock_address = "<%= expansion('https://gitlab.com/api/v4/projects/[PROJECT_ID]/terraform/state/:ENV/lock') %>"
    username = "[GITLAB_USER]"
    password = "[GITLAB_PERSONAL_ACCESS_TOKEN]"
  }
```

Having all values populated, `TS_ENV=prod terraspace init [STACK]` works, but for obvious reasons I can't have the `password` field pre-populated here.

Once the password field is removed, I see the following error after running terraspace init:

```
2021/11/24 14:11:27 [DEBUG] GET https://gitlab.com/api/v4/projects/[PROJECT_ID]/terraform/state/prod
Error refreshing state: HTTP remote state endpoint requires auth
Error running command: terraform init -get -input=false
```

Official Gitlab documentations (for terraform) suggests calling init with `-backend-config="password=[GITLAB_PAT]"`, but `terraspace init` doesn't seem to accept extra parameters:

`ERROR: "terraspace init" was called with arguments ["lke", "-backend-config=password=123"]`

Any clarity around this issue would be helpful.

**Comment by tongueroo** [comment]
Currently, the http backend is yet not supported. Will consider PRs. No sweat either way of course. Unsure when will get to this yet but do want to add support.

**Comment by yisyang** [comment]
@tongueroo Thank you for responding so quickly, and editing the responses too! Not to mention it's right before everyone take off for the holidays!

I'm sure your solution `<%= ENV["VAR"] %>` is enough for my use case storing init configs as masked vars on Gitlab, though unfortunately I'm blocked from testing at the moment. In my hurry I tried to do `bundle update` as the docs suggested, and ran into [gem faraday 0.17.4 dependency issue](https://github.com/boltops-tools/terraspace/issues/137) that I've yet not being able to resolve for hours despite trying fresh installs and different versions of ruby on rbenv and clearing project dir and cache dirs... Never seen issues this persistent before with npm or python.

Anyways, please don't reply this week. Enjoy your holidays!

**Comment by tongueroo** [comment]
Thanks for the holiday wishes! It’s no big deal. Got a little time right now. 

For the dependencies issue. I dislike having to prepend “bundle exec” myself. Try a shim: https://terraspace.cloud/docs/misc/shim/

**Comment by yisyang** [comment]
Fresh `gem install terraspace` worked!

Also ran into https://github.com/boltops-tools/terraspace/issues/131, but found a very ugly workaround for the time being...

Tested and the "<%= ENV["FOO"] %>" works fine. 👍 

backend.tf
```
terraform {
  backend "http" {
    address         = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV') %>"
    lock_address    = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV/lock') %>"
    unlock_address  = "<%= expansion('https://gitlab.com/api/v4/projects/31586394/terraform/state/:ENV/lock') %>"
    username        = "<%= ENV["CI_USER"] %>"
    password        = "<%= ENV["CI_PAT"] %>"
  }
}
```

**Comment by tongueroo** [comment]
Docs: https://terraspace.cloud/docs/config/backend/examples/gitlab/
