### ISSUE TITLE
terraspace build creates \r\n and invalid TF code on Windows

### ISSUE THREAD

**Issue by CumpsD** [boltops-tools/terraspace#209]
## Checklist

- [x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  Windows 11      |
| Terraform        |   1.1.5      |
| Terraspace       |    1.1.3     |

---

## Expected Behaviour

`terraspace build` files exactly as they are

## Current Behavior

Files using CRLF as line endings get formatted incorrectly, causing TF to fail.

## Step-by-step reproduction instructions

I have this in my `Terrafile`:

```
mod "lambda", source: "terraform-aws-modules/lambda/aws"
```

One of the files looks like this in the vendor folder:

![image](https://user-images.githubusercontent.com/1201644/154553718-bee663cc-5f56-4993-b20e-b9e0f29c9f92.png)

After running `terraspace build` it gets turned into this:

![image](https://user-images.githubusercontent.com/1201644/154553858-fb774ef1-a907-46ec-8d13-d541a3df4cc8.png)

Which causes a lot of errors:

![image](https://user-images.githubusercontent.com/1201644/154553931-506fb461-3662-42e4-ac41-ee2e42120f52.png)

If I run `dos2unix` on the files, it works.

## Solution Suggestion

Find out why Ruby does this to the files and avoid it if possible?

**Comment by tongueroo** [comment]
Wondering if this quick fix will do the trick. https://stackoverflow.com/questions/30195652/how-to-stop-ruby-automatically-adding-carriage-returns

Try throwing this at the top of:

lib/terraspace.rb

```ruby
$\ = "\n"
```

**Comment by CumpsD** [comment]
Sadly enough it didn't work :(

It only happens with `*.tf` files btw, readme.md and others are copied correctly.

**Comment by tongueroo** [comment]
File is written here. https://github.com/boltops-tools/terraspace/blob/37fdf43d02ccae63e60e6cc3a61afbe4b62bfb5f/lib/terraspace/compiler/writer.rb#L37 Thanks for giving it a try.

**Comment by CumpsD** [comment]
```ruby
    def write(content)
      FileUtils.mkdir_p(File.dirname(dest_path))
      if content.respond_to?(:path) # IO filehandle
        FileUtils.cp(content.path, dest_path) # preserves permission
      else # just content
        my_file = Tempfile.new("tmp.tf")
        my_file.binmode
        my_file.print content
        my_file.close
        FileUtils.mv(my_file.path, dest_path)

        # IO.write(dest_path, content)
      end
      logger.debug "Created #{Terraspace::Util.pretty_path(dest_path)}"
    end
```

This writes it out correctly :D

**Comment by tongueroo** [comment]
Sweet 🎊 Will take a look adding a write shim method that uses that for Windows and regular IO.write for other OSes. On the road right now. Feel free to have a go at a PR. No sweat either way. Hope to get to it. Probably over the weekend.
