### ISSUE TITLE
String interpolation doesn't work

### ISSUE THREAD

**Issue by mgzenitech** [boltops-tools/terraspace#229]
## Checklist

- [x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |         |
| Terraform        |         |
| Terraspace       |         |
| Ruby             |         |

---

## Code Sample

```hcl2
terraform {
  backend "s3" {
    bucket = "<%= normalize('ts-state-' + seed) %>"
    ...
  }
}

terraform {
  backend "s3" {
    bucket = "<%= normalize('ts-state-#{seed}') %>"
    ...
  }
}
```

**Comment by tongueroo** [comment]
String interpolation requires double quotes in Ruby 😄

So this should work:

```ruby
terraform {
  backend "s3" {
    bucket = "<%= normalize("ts-state-#{seed}") %>"
  }
}
```

Also, testing in an interactive ruby client IRB can help to figure things out. Example:

    $ irb
    3.1.1 :001 > x = "bar"
     => "bar" 
    3.1.1 :002 > y = "foo-#{x}"
     => "foo-bar" 
    3.1.1 :003 > z = 'foo-#{x}'
     => "foo-\#{x}" 
    3.1.1 :004 >
