### ISSUE TITLE
.env TS_PROJECT don't get evaluated in S3 backend key

### ISSUE THREAD

**Issue by matteo-mazzanti-aws** [boltops-tools/terraspace#241]
## Checklist

- [ x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/ (v2.0.1)
- [ x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | macos 11.6.5 |
| Terraform | v1.1.4 |
| Terraspace | v2.0.1 |
| Ruby | v3.1.2p20 |

---

## Expected Behaviour

Defined variable TS_PROJECT in .env file (file in TS root folder)
Backend S3 key value has expansion that includes PROJECT
The tf state in S3 bucket is inside a folder named as TS_PROJECT

## Current Behavior
The tf.state is inside folder named 'main' (that is teh default TS_PROJECT value, I suppose)

## Step-by-step reproduction instructions
Create .env file with TS_PROJECT in TS root folder
Create provider file with expansion that includes PROJECT.
Create main.tf with a S3 bucket resource for test
Run TS up

## Code Sample
- .env
```
TS_PROJECT="cb"
AWS_REGION="eu-central-1"
```
- backend.tf
```
terraform {
  backend "s3" {
    bucket         = "<%= expansion('terraform-state-:ACCOUNT-:REGION-:ENV') %>"
    key            = "<%= expansion(':PROJECT/:TYPE_DIR/:APP/:ROLE/:MOD_NAME/:ENV/:EXTRA/:REGION/terraform.tfstate') %>"
    region         = "<%= expansion(':REGION') %>"
    encrypt        = true
    dynamodb_table = "terraform_locks"
  }
}
```

**Comment by tongueroo** [comment]
I see. The `:PROJECT` variable was mapped only to the `config.cloud.project = ...` setting. https://terraspace.cloud/docs/cloud/config/  Also added a mapping to TS_PROJECT now in #242
