### ISSUE TITLE
terraspace plan return error bad URI.

### ISSUE THREAD

**Issue by RiddlerKnight** [boltops-tools/terraspace#254]
I have upgraded terraspace from 2.0.0 to 2.1.4 and terraform 1.2.5 then I tried to "terraspace plan <stack>", I got an error like this.

![image](https://user-images.githubusercontent.com/15905772/180170350-4e4067df-31c1-470b-ab60-b44d801cc99a.png)

I'm not sure that what function interact with my git remote url?

When I downgrade to 2.0.3, it work fine.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |      wsl ubuntu 20.04   |
| Terraform        |        1.2.5 |
| Terraspace       |        2.1.4 |
| Ruby             |        3.0.3p157 |

**Comment by tongueroo** [comment]
Fixed in #255 and released in 2.1.5. It would be useful you can email tongueroo@gmail.com the general form of the git repo, so can improve that logic in the future. No sweat either way. Thanks for the report.
