### ISSUE TITLE
`terraspace import` doesn't work

### ISSUE THREAD

**Issue by vsinha** [boltops-tools/terraspace#292]
It appears that terraspace doesn't handle parameters properly when calling terraspace import. Potentially, it's just that this error message needs updating. My reading of the message is that terraspasce was in fact called with two arguments.

```bash
$ terraspace import helm_release.foo my-k8s-namespace/foo-helm-deployment 
ERROR: "terraspace import" was called with arguments ["helm_release.foo", "my-k8s-namespace/foo-helm-deployment"]
Usage: "terraspace import ADDR ID"
```

## Checklist

- [X] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  M1 MacOS darwin_arm64       |
| Terraform        |    1.3.7    |
| Terraspace       |   2.2.3      |
| Ruby             |    3.2.0     |

**Comment by vsinha** [comment]
realizing now perhaps the correct invocation is `terraspace <stack name> <resource> <helm release>` ?

**Comment by vsinha** [comment]
The docs say: 
```
terraspace import ADDR ID
```

And then immediately after that invoke terraspace with:
```
terraspace import vpc module.vpc.aws_vpc.this vpc-000782e4951a734c7
```

Should the docs say `terraspace import STACK ADDR ID` instead @tongueroo ?

**Comment by tongueroo** [comment]
Oh I see. Reopened
