### ISSUE TITLE
Remove from and add to state

### ISSUE THREAD

**Issue by phenry20** [boltops-tools/terraspace#45]
## Summary

I would like to manually remove an item from the state. I can do this via `terraform state rm ....`, but I don't see such a command with terraspace. Also I haven't  seen any functionality to add existing resources to the state. This would also be valuable.

## Motivation

Sometimes automating the removal of items it's feasible or sometimes it's done manually in the UI. In those use cases terraspace breaks because it's referencing a resource that doesn't exist. Also if you add in terraspace later into the project it would be nice to add them to the state file so terraform can manage the resources

**Comment by tongueroo** [comment]
Cool. Yup. Will take a look in time. Know you already mentioned that you can do it with just the pure terraform cli. Posting info here for others also:

    terraspace new project infra --examples
    terraspace build demo
    cd .terraspace-cache/us-west-2/dev/stacks/demo
    terraform init
    terraform apply -auto-approve
    terraform state pull
    terraform state list

**Comment by augustgerro** [comment]
Also, trying to list all existing resources with `terraspace state list` but nothing. 
But with terragrunt it's works well `terragrunt state list `

**Comment by tongueroo** [comment]
Initial version of terraspace state command was added as part of #87
