### ISSUE TITLE
Publish latest alpine/terraspace container image to hub.docker.com

### ISSUE THREAD

**Issue by ron1** [boltops-tools/terraspace#53]
## Summary
Publish latest alpine/terraspace container image to hub.docker.com

## Motivation
In some environments, it is problematic to install/configure a ruby runtime with a gem such as Terraspace. As an alternative, support running Terraspace from a container. Terragrunt provides such a container here: https://github.com/alpine-docker/terragrunt. The Terragrunt container on dockerhub has been downloaded over 1 million times. Terraspace should consider following suit and defining git repo https://github.com/alpine/terraspace for use in pushing the latest Terraspace container image to dockerhub.

A Terraspace container image would also support native k8s CI pipelines that want to use Terraspace to manage infrastructure via a gitops model.

Finally, the Terraform community is accustomed to working with a dependency-free terraform Go binary and seamlessly-downloaded plugins. Any Ruby-specific dependencies and complexity should be hidden as much as possible in order to increase adoption within the Terraform community.

See current attempt to define a working alpine/terraspace container [here](https://github.com/boltops-tools/terraspace/issues/52).

**Comment by tongueroo** [comment]
See #52. Handled there.
