### ISSUE TITLE
Support for JSON formatted plan output

### ISSUE THREAD

**Issue by MatthiasScholzTW** [boltops-tools/terraspace#57]
## Summary

Please provide support to output the result of a `terraspace plan` and `terraspace all plan` run as JSON.

## Motivation

Terraform provides support for the JSON format since version 0.12.
The JSON format can be used to pass the results of a plan into a static code analysis before applying the changes, e.g. `conftest`.

## Guide-level explanation

The existing CLI could be extended to support `--json` as an additional parameter.
Resulting in commands like:
- `terraspace plan <stack> --out <stack>.tfplan.json --json`
- `terraspace all plan --json`

## Drawbacks

The feature is available in terraform >=0.12.
Support for older versions might be cumbersome since additional tooling would be needed.

## Unresolved Questions

- Naming convention for file names for the `terraspace all plan --json` call.

**Comment by MatthiasScholzTW** [comment]
It seems this feature is already covered with `terraspace show <stack> --json`.

Nevertheless using `terraspace show <stack> --plan <stack>.tfplan fails due to `State read error: Error loading statefile: open <stack>.tfplan: no such file or directory`. The `<stack>.tfplan` file is locate at the root of the repository. It was created using `terraspace plan <stack> --out <stack>.tfplan`.

Should this feature request be closed and an issue report be formulated instead?

**Comment by tongueroo** [comment]
Closed in favor of #156

**Comment by exoemay** [comment]
I know this is a bit later, but is this feature really included in #156? I haven't found a way to output json-format plan files via `terraspace all plan`. What is the syntax to output json plan files?
