### ISSUE TITLE
Package Terraspace as a Linux AppImage (see https://appimage.org/)

### ISSUE THREAD

**Issue by ron1** [boltops-tools/terraspace#62]
## Summary

Terraform and Terragrunt users are accustomed to the simple, zero-dependency, installation of go binaries. For these users, installation of a Ruby Gem is problematic. Also, many of these users do not have root privileges on their hosts which makes package manager-based installations problematic. These non-root users cannot install Docker either. So, to target these users, consider packaging Terraspace as an AppImage (see https://appimage.org/).

## Motivation

Simplify installation of Terraspace for non-root users who cannot install Terraspace using a package manager and cannot install Docker to use the Terraspace docker image.

**Comment by tongueroo** [comment]
Would like to do this but seems like it'll take some effort. Happy to consider PRs. No sweat either way of course. Going to move close and label backlog for now.
