### ISSUE TITLE
How can i refer output of stack from different TS_ENV

### ISSUE THREAD

**Issue by k1rk** [boltops-tools/terraspace#65]
How can i use output of stack from different TS_ENV?

So for example i'm not using multiple account setup, and i want to have some common IAM resources

Or if i have only one account for user management. and then in other accounts i want to refer users in assume role policy

**Comment by tongueroo** [comment]
Currently, not possible. Would have to think about how to approach that. 🧐

Note, am trying to keep GitHub issues decently clean and questions to be posted elsewhere. Thanks!
