### ISSUE TITLE
Terraspace bundle install example stacks

### ISSUE THREAD

**Issue by syunull** [boltops-tools/terraspace#77]
## Checklist

- [x] Upgrade Terraspace: Are you using the latest version of Terraspace? This allows Terraspace to fix issues fast. There's an Upgrading Guide: https://terraspace.cloud/docs/misc/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | macOS Big Sur version 11.2 |
| Terraform        | v0.14.6 |
| Terraspace       | 0.5.10 |
| Ruby             | 3.0.0p0 |

---

## Expected Behaviour
Install modules in vendor directory

## Current Behavior
Install modules in vendor directory plus adds all example stacks

## Step-by-step reproduction instructions
Specify module in Terrafile and run terraspace bundle

## Code Sample
#Terrafile
stack_options(purge: true)
mod "eks", source: "terraform-aws-modules/eks/aws", stacks: :all, version: "14.0.0"
mod "iam", source: "terraform-aws-modules/iam/aws", stacks: :all, version: "3.8.0"
mod "vpc", source: "terraform-aws-modules/vpc/aws", stacks: :all, version: "2.70.0"

## Solution Suggestion
Don't add sample stacks

**Comment by tongueroo** [comment]
Remove `stacks: :all` from the Terrafile and the example stacks will not be added. Docs: https://terraspace.cloud/docs/terrafile/options/stack/#all-examples
