### ISSUE TITLE
Terraspace support for Hashicorp Vault secret engine

### ISSUE THREAD

**Issue by Roxyrob** [boltops-tools/terraspace#82]
Hi,
along with "AWS Secrets Manager", "AWS SSM Parameter Store", "Azure Key Vault", "Google Secrets Manager" as secrets angine It'll be an option the suppor for **hashicorp vault** ?

**Comment by tongueroo** [comment]
Yes, would like to have that. Unsure when though, it's a matter of time. Will consider PRs. Of course, no sweat either way 👍 Thanks!

**Comment by Voziv** [comment]
When googling for hashicorp vault support I came across this issue. Was it meant to be closed? Feels like it was accidentally closed when commenting.

**Comment by tongueroo** [comment]
Naw. Closed to keep issues clean. If someone has further interest, hope they can open a feature request issue with the template filled out and link to this one.
