### ISSUE TITLE
Is it possible to use test-kitchen as the test framework

### ISSUE THREAD

**Issue by ChineduUzoka** [boltops-tools/terraspace#86]
One of the blockers here at the consultancy i work for is that the Terraform test framework we use is test-kitchen or more specifically kitchen-terraform. Is it possible to use test-kitchen instead of rspec-terraspace or integrate the two but drive it from test-ktichen?

**Comment by tongueroo** [comment]
Not currently. Would like to see this. Will consider PRs. Of course, no sweat either way. Putting in backlog until there’s time.

**Comment by ChineduUzoka** [comment]
Thanks for your reply - my ruby skills suck but do like a challenge.  This is a showstopper right now.  I have been looking at ways of integrating the two but really do not know where to start. The test-kitchen hook feature would be my first bet.  If test-kitchen can start the terraspace test harness figure out where the terraform scripts are copied to then take over from there that would be my first iteration.
ill spend some time looking at - im about to start an engagement and would rather use Terraspace than Terragrunt which has become quite bloated imo
